const express = require('express');
const upiTransactionModel = require('../model/upiTransactionModel');

const router = express.Router()

router.post('/', async (req, res) => {
    const upiTransactionData = new upiTransactionModel({
        userId: req.body.userId,
        upiNumber: req.body.upiNumber,
        orderId: req.body.orderId,
        transactionStatus: 'SUCCESS', // TODO : generated after save success
        transactionDate: new Date().toISOString() // TODO : generated by this service
    })
    try { 
        const dataToSave = await upiTransactionData.save();
        // TODO : make a Notifications API Call saying that payment is SUCCESS
        res.status(200).json(dataToSave)
    } catch (error) {
        // TODO : make a Notifications API Call saying that payment is FAILED
        res.status(400).json({ message: error.message })
    }
})

module.exports = router;
